learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Learning log API",
        default_version='v1',
        description='API documentation for application Learning Log using Swagger'
    ),
    public=True,
    permission_classes = (permissions.AllowAny,),

)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('learning_logs.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


    
]

learning_logs/urls.py
"""Definiuje wzroce url dla learning_logs"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #strona głowna
    path('', views.index,name='index'),
    #Wyświetlanie wszystkich tematów
    path('topics/', views.topics,name='topics'),
    #Strona szczegółowa dotycząca poszczególnego tematu
    path('topics/(<int:topic_id>)/',views.topic,name='topic'),
    #Dodawanie nowego tematu
    path('new_topic/',views.new_topic,name='new_topic'),
    #Dodawanie nowego wpisu
    path('new_entry/(<int:topic_id>)/',views.new_entry,name='new_entry'),
    #Strona przeznaczona do edycji wpisu
    path('edit_entry/<int:entry_id>/', views.edit_entry,name="edit_entry")
    

]

users/urls.py
"""Definiuje wzorce adresów URL dla apliakcji users"""

from django.urls import path,include
from . import views

app_name = 'users'
urlpatterns = [
#Dołączanie domyślnych adresów URL uwierzytelniania
path('logout/',views.user_logout,name='user_logout'),
path('', include('django.contrib.auth.urls')),
#Strona rejestracji
path('register/',views.register,name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """Temat definiowany przez użytkownika"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Zwraca reprezentacje modelu w postaci ciągu tekstowego"""
        return self.text
    
class Entry(models.Model):
    """Informacje, wpisy odnośnie konkretnego tematu"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Zwaraca reprezentacje modelu w postaci ciągu tesktowego"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,Http404
from rest_framework.decorators import api_view

from .models import Topic,Entry
from .forms import TopicForm,EntryForm


def index(request):
    """Strona głowna dla aplikacji Learning log."""
    return render(request, 'learning_logs/index.html')

@api_view(['GET'])
@login_required
def topics(request):
    """Wyświetlanie wszystkich tematów"""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@api_view(['GET'])
@login_required
def topic(request,topic_id):
    """Wyświetla pojedyńczy temat i wszystkie powiązane z nim wpisy"""
    topic = Topic.objects.get(id=topic_id)
    #Upewniamy się że dany temat należy do użytkownika
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request,'learning_logs/topic.html',context)

@api_view(['POST', 'GET'])
@login_required
def new_topic(request):
    """Dodaj nowy temat"""
    if request.method != "POST":
        #Nieprzekazano żadnych danych, należy utworzyć pusty formularz.
        form = TopicForm()
    else:
        #Przekazano dane i należy je przetworzyć
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topics = form.save(commit=False) 
            new_topics.owner = request.user
            form.save()
            return redirect('learning_logs:topics')
    
    #Wyświetlanie pustego formularza
    context = {'form': form}
    return render(request,'learning_logs/new_topic.html', context)

@api_view(['POST', 'GET'])
@login_required
def new_entry(request, topic_id):
    """Dodanie nowego wpisu dla konkretnego tematu"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #Nie przekazano danych, należy utworzyć pusty formularz
        form = EntryForm()
    else:
        #Przekazano dane za pomocą żądania POST
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)
        
    #Wyświetlanie pustego formularza
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html',context)

@api_view(['POST', 'GET'])
@login_required
def edit_entry(request,entry_id):
    """Edycja insteniejącego wpisu"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #Nie przekazano danych, należy utworzyć pusty formularz
        form = EntryForm(instance=entry)
    else:
        #Przekazano dane za pomocą żądania POST
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic.id)
    
    context = {'entry': entry, 'topic': topic,'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view


@api_view(['POST', 'GET'])
def register(request):
    """Rejestracja nowego użytkownika"""
    if request.method != "POST":
        #wyświetlanie pustego formularza
        form = UserCreationForm()
    else:
        #Przetwarzanie wypełnionego formularza
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            #Zalogowanie użytkownika, a następnie przekierowanie na 
            #główna strone
            login(request,new_user)
            return redirect('learning_logs:index')
        
    #Wyświetlenie pustego formularza
    context = {'form': form}
    return render(request, 'registration/register.html',context)

@api_view(['POST', 'GET'])
@login_required
def user_logout(request):
    logout(request)
    return render(request,'registration/logged_out.html', {})

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning Log</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
    Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics'%}">
            Topics</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text"}>Hello, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
          {% endif %}
        </ul>
      </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

<footer class="blog-footer" 
style="padding: 2.5rem 0;
  color: #999;
  text-align: center;
  background-color: #f9f9f9;
  border-top: .05rem solid #e5e5e5;
  ">
  <p>Project from the book 
    <a href="https://nostarch.com/pythoncrashcourse2e/">Python Crash Course</a> 
    by Eric Matthes.</p>
  <p style="margin-bottom: 0;">Made by 
    <a href="https://github.com/Elahi-cs">Elahi Concha</a>.</p>
</footer>
</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edycja wpisu:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Dodaj temat</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the topics
        you're learning about. Whenever you learn something new about a topic,
        make an entry summarizing what you've learned.</p>

    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
        role="button">Begin &raquo;</a>
    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
    {% endif %}
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Dodaj nowy wpis:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Dodaj wpis</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Dodaj nowy temat:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Dodaj temat</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

{% for entry in entries %}
  <div class="card mb-3">
    <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
        edit entry</a></small>
    </h4>
    <div class="card-body">
      {{ entry.text|linebreaks }}
    </div>   
  </div>  
{% empty %}
  <p>There are no entries for this topic yet.</p>
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
<ul>
  {% for topic in topics %}
    <li><h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
  {% empty %}
    <li><h3>No topics have been added yet.</h3></li>
  {% endfor %}
</ul>

<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}